Homework #1. Three basic tests with fixtures and arrays
IvanDruzhchenk0/telemart-playwright-automation pull request #3
Opened 2024-08-12 04:40 UTC by IvanDruzhchenk0

2024-08-13 16:25 UTC, qa-senpai requested changes

2024-08-13 16:25 UTC, qa-senpai commented on Project/Fixtures/fixturePages.ts
> +    searchResultsPage: ({page}, use) => {
я не певен що це пейджа...

2024-08-13 16:25 UTC, qa-senpai commented on Project/Pages/catalogPage.ts
> +export class CatalogPage {
чому назва файла з маленької букви?

2024-08-13 16:25 UTC, qa-senpai commented on tests/filterAndOrder.spec.ts
> +    "filterOption301-1013-22721",
я на стрімі розказував як уникати таких моментів за допомогою enum

2024-08-13 16:25 UTC, qa-senpai commented on tests/filterAndOrder.spec.ts
> +    "https://telemart.ua/ua/monitors/samsung/"
https://telemart.ua/ повинно бути в basePage в playwright.config.ts

2024-08-13 16:25 UTC, qa-senpai commented on tests/filterAndOrder.spec.ts
> +});
а де перевірки?

2024-08-13 16:25 UTC, qa-senpai commented on tests/openByPromoBanner.spec.ts
> +  await homePage.clickOnCityModal("Так, вірно");
краще так не робити, твоїми тестами будуть користуватись не тільки україномовні люди. 
ховай це в PageObject

2024-08-14 16:55 UTC, IvanDruzhchenk0 commented on Project/Fixtures/fixturePages.ts
> +    searchResultsPage: ({page}, use) => {
я би сказав, що так, бо в неї дизайн і наповнення відрізняється від усіх інших. ось, як приклад, є така:
https://telemart.ua/ua/promotions/msi-38-gifts-birthday.html

а є трохи інша, з іншим наповненням:
https://telemart.ua/ua/promotions/xiaomi-at-a-super-price.html

і у кожної вшито 'promotions' в URl. тому я просто переназвав трохи її, аби було зрозуміліше, і вирішив так залишити.

коли б в мене з'явились тести на загальну пейджу 'Акції' (https://telemart.ua/ua/promotions/), я би може якось її інтегрував туди. але поки думаю, що можна зберігати окремо для зручності

2024-08-14 16:55 UTC, IvanDruzhchenk0 commented on Project/Pages/catalogPage.ts
> +export class CatalogPage {
fixed

2024-08-14 16:55 UTC, IvanDruzhchenk0 commented on tests/filterAndOrder.spec.ts
> +    "filterOption301-1013-22721",
переробив

2024-08-14 16:55 UTC, IvanDruzhchenk0 commented on tests/filterAndOrder.spec.ts
> +    "https://telemart.ua/ua/monitors/samsung/"
fixed

2024-08-14 16:55 UTC, IvanDruzhchenk0 commented on tests/filterAndOrder.spec.ts
> +});
всі перевірки зберігаю в методах PO

2024-08-14 16:55 UTC, IvanDruzhchenk0 commented on tests/openByPromoBanner.spec.ts
> +  await homePage.clickOnCityModal("Так, вірно");
Fixed

2024-08-14 17:05 UTC, IvanDruzhchenk0 commented on Project/Pages/catalogPage.ts
> +export class CatalogPage {
дивно, але чомусь я не бачу в git-і, щоб вона перейменованим показувало файли. локально назви всі правильні
<img width="301" alt="image" src="https://github.com/user-attachments/assets/dc96483b-eeae-41c2-b530-ed9004e2cad4">

2024-08-15 13:27 UTC, IvanDruzhchenk0 commented on Project/Pages/checkoutPage.ts
fixed locator

2024-08-15 13:28 UTC, IvanDruzhchenk0 commented on Project/Pages/filteringResultsPage.ts
same - changed method to avoid flakiness based on Playwright documentation

2024-08-15 13:28 UTC, IvanDruzhchenk0 commented on Project/Pages/productPage.ts
regexp to avoid failing locators when there is a " or ' signs inside product name

2024-08-15 13:29 UTC, IvanDruzhchenk0 commented on Project/Pages/catalogPage.ts
> +      await this.page.waitForResponse(response => response.url().includes('https://telemart.ua/ua/monitors/filter/') && response.status() === 200 && response.request().method() === 'GET', {timeout: 6
added waitForResponse to avoid flakiness during last filter selection. without checking the response filter was not applying from time to time

2024-08-15 13:30 UTC, IvanDruzhchenk0 commented on Project/Pages/checkoutPage.ts
> +    await expect(this.page.locator(`//input[@id="customerLastname"][@value='${surname}']`)).toBeVisible();
fixed locator

2024-08-15 13:30 UTC, IvanDruzhchenk0 commented on Project/Pages/filteringResultsPage.ts
> +    await expect(filterSelection).toHaveCount(numberOfFilters);
same - changed method to avoid flakiness based on Playwright documentation

2024-08-15 13:30 UTC, IvanDruzhchenk0 commented on Project/Pages/productPage.ts
> -    return productName;
regexp to avoid failing locators when there is a " or ' signs inside product name

2024-08-15 13:30 UTC, IvanDruzhchenk0 commented on tests/filterAndOrder.spec.ts
>    const expectedParameters = [
clean-up to make tests more stable

2024-08-15 13:32 UTC, IvanDruzhchenk0 commented on Project/Pages/productPage.ts
>    }
regexp to avoid failing locators when there is a " or ' signs inside product name

2024-08-22 12:31 UTC, merged